[2024-06-25T16:38:19.935+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T16:38:19.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_exo_data_to_s3.transform_nasa_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-25T16:38:19.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_exo_data_to_s3.transform_nasa_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-06-25T16:38:19.960+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-06-25T16:38:19.970+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_nasa_data> on 2024-06-24 00:00:00+00:00
[2024-06-25T16:38:19.977+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=54) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T16:38:19.978+0000] {standard_task_runner.py:63} INFO - Started process 58 to run task
[2024-06-25T16:38:19.978+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_exo_data_to_s3', 'transform_nasa_data', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/etl_exo.py', '--cfg-path', '/tmp/tmpqzwx4vua']
[2024-06-25T16:38:19.980+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask transform_nasa_data
[2024-06-25T16:38:20.014+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_exo_data_to_s3.transform_nasa_data scheduled__2024-06-24T00:00:00+00:00 [running]> on host 95b3b965c5b1
[2024-06-25T16:38:20.078+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='nasa_exo_data_to_s3' AIRFLOW_CTX_TASK_ID='transform_nasa_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T00:00:00+00:00'
[2024-06-25T16:38:20.079+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T16:38:20.282+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T16:38:20.282+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_exo.py", line 38, in transform_data
    data = response.json()
           ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'json'
[2024-06-25T16:38:20.292+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nasa_exo_data_to_s3, task_id=transform_nasa_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20240625T163819, end_date=20240625T163820
[2024-06-25T16:38:20.305+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 72 for task transform_nasa_data ('list' object has no attribute 'json'; 58)
[2024-06-25T16:38:20.352+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T16:38:20.374+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T16:38:20.377+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
